platform :ios, '9.0'
use_frameworks!

target 'Fristrations' do
    pod 'Firebase', '>= 2.5.1'
	pod 'HTMLReader'
	pod 'Kanna'
end

target 'FristrationsTests' do

end

target 'FristrationsUITests' do

end

