platform :ios, '9.0'
use_frameworks!

target 'Fristrations' do
	pod 'Firebase', '>= 2.5.1'
	pod 'FBSDKLoginKit', '>= 4.11'
	pod 'FBSDKCoreKit', '>= 4.11'
end

target 'FristrationsTests' do

end

target 'FristrationsUITests' do

end

