platform :ios, '9.0'
use_frameworks!

target 'Fristrations' do
    pod 'Firebase'
	pod 'HTMLReader'
	pod 'Kanna'
end

target 'FristrationsTests' do

end

target 'FristrationsUITests' do

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end